
makinacorpus_autocomplete_find:
    path: autocomplete/{type}
    controller: MakinaCorpus\Autocomplete\AutocompleteController::find
    defaults:
        query: ~
        limit: 30
        page: 1
    requirements:
        limit: \d+
        page: \d+
